.TH "ARCHIPA\-KUBERNETES" "1" "September 2017" "" ""
.SH "NAME"
\fBarchipa-kubernetes\fR
.P
archipa kubernetes <path> [\-\-view\-ast, \-\-imports = url1,url2, \-\-searchIn = dir1, dir2\.\.\.|\-\-json|\-\-yaml]
.SH DESCRIPTION
.P
<path>:
Compile the ICL file located in the specified path and prints the generated YAML output\.
JSON output is also supported by passing the \fB\-\-json\fP flag\.
.P
\-\-view\-ast: 
Displays the generated AST and not the actual generated JSON/YAML output\.
.P
\-\-imports:
This is a list of ICL files that needs to be included at compile time\.
.P
\-\-searchIn:
Those are the directories that needs to be searched in for ICL dependencies

