/** Declaration file generated by dts-gen */

export = download_git_repo;

declare function download_git_repo(repo: any, dest: any, opts: any, fn: any): void;

declare namespace download_git_repo {
    const prototype: {
    };

}

